version: "3.8"
services:
    php:
        container_name: php-container
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "7000:80"
        volumes:
            - ./src:/var/www/html
    iservice_db:
        container_name: iservice_db
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: iservice
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
        driver: local
